'use client';
import {useMemo,useState} from 'react';
import AppShell from '@/components/AppShell';
import {Modal,PageHeader,Status} from '@/components/UI';

type Task={id:number;title:string;assignee:string;assignedBy:string;due:string;time:string;priority:string;status:string;related:string;notes:string};
const seed:Task[]=[
{id:1,title:'Call Ari after property viewing',assignee:'Self',assignedBy:'Roj Ahmed',due:'2026-07-30',time:'13:00',priority:'High',status:'Not started',related:'Ari Hassan · Empire Pearl 2BR',notes:''},
{id:2,title:'Prepare owner documents checklist',assignee:'Sara Karim',assignedBy:'Office Assistant',due:'2026-07-31',time:'09:30',priority:'Normal',status:'In progress',related:'Lana Kareem',notes:''},
{id:3,title:'Confirm villa viewing',assignee:'Roj Ahmed',assignedBy:'Self',due:'2026-07-29',time:'17:00',priority:'Urgent',status:'Waiting',related:'Dream City Villa 14',notes:''},
{id:4,title:'Update property photos',assignee:'Office Assistant',assignedBy:'Sara Karim',due:'2026-08-02',time:'11:00',priority:'Low',status:'Not started',related:'Gulan Office 402',notes:''}];
export default function TasksModule(){const [rows,setRows]=useState(seed),[show,setShow]=useState(false),[filter,setFilter]=useState('All');const list=useMemo(()=>filter==='All'?rows:rows.filter(r=>r.status===filter),[rows,filter]);
function add(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setRows([{id:Date.now(),title:String(f.get('title')),assignee:String(f.get('assignee')),assignedBy:'Self',due:String(f.get('due')),time:String(f.get('time')),priority:String(f.get('priority')),status:'Not started',related:String(f.get('related')),notes:String(f.get('notes'))},...rows]);setShow(false)}
return <AppShell><PageHeader title="Tasks" subtitle="Assign work, follow-ups and reminders" action="New Task" onAction={()=>setShow(true)}/><div className="task-tabs">{['All','Not started','In progress','Waiting','Completed','Cancelled'].map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div><div className="task-board"><div className="task-list-head"><span>Task</span><span>Assigned to</span><span>Due</span><span>Priority</span><span>Status</span></div>{list.map(r=><article className="task-row" key={r.id}><div><strong>{r.title}</strong><small>{r.related}</small><small>Assigned by {r.assignedBy}</small></div><span>{r.assignee}</span><span>{r.due}<small>{r.time}</small></span><Status tone={r.priority==='Urgent'?'bad':r.priority==='High'?'warn':'neutral'}>{r.priority}</Status><select value={r.status} onChange={e=>setRows(rows.map(x=>x.id===r.id?{...x,status:e.target.value}:x))}>{['Not started','In progress','Waiting','Completed','Cancelled'].map(x=><option key={x}>{x}</option>)}</select></article>)}</div>{show&&<Modal title="Create Task" onClose={()=>setShow(false)} wide><form onSubmit={add}><div className="form-grid"><label className="span-2">Task title *<input name="title" required/></label><label>Assign to *<select name="assignee"><option>Self</option><option>Roj Ahmed</option><option>Sara Karim</option><option>Office Assistant</option><option>Branch Manager</option></select></label><label>Priority<select name="priority"><option>Normal</option><option>Low</option><option>High</option><option>Urgent</option></select></label><label>Due date *<input name="due" type="date" min={new Date().toISOString().slice(0,10)} required/></label><label>Due time<input name="time" type="time" step="900"/></label><label className="span-2">Related contact, property or deal<input name="related" placeholder="Optional"/></label><label className="span-2">Notes<textarea name="notes" rows={3}/></label><label className="span-2 check-line"><input type="checkbox" defaultChecked/>In-app reminder 30 minutes before</label></div><div className="modal-actions"><button type="button" className="btn ghost" onClick={()=>setShow(false)}>Cancel</button><button className="btn">Create Task</button></div></form></Modal>}</AppShell>}
