const state={page:'dashboard',theme:'light',propertyFilter:'All',leadFilter:'All'};
const nav=[['Workspace',[['dashboard','▦','Dashboard'],['leads','◎','Leads & Pipeline'],['clients','◉','Clients'],['properties','⌂','Properties'],['map','⌖','Property Map']]],['Operations',[['whatsapp','◫','WhatsApp Hub'],['calendar','□','Calendar'],['tasks','✓','Tasks'],['contracts','▤','Contracts'],['finance','$','Finance']]],['Insights',[['reports','↗','Reports'],['team','♙','Team & Commissions']]],['System',[['packages','✦','Packages & Modules'],['settings','⚙','Settings']]]];
const leads=[
{id:1,name:'Ahmed Kareem',phone:'+964 750 123 8891',source:'Facebook',budget:'$180k–$220k',agent:'Sara',status:'Viewing',score:92,last:'12 min ago'},
{id:2,name:'Dilan Hassan',phone:'+964 751 554 1102',source:'WhatsApp',budget:'$95k–$130k',agent:'Omar',status:'New',score:78,last:'25 min ago'},
{id:3,name:'Mohammed Rauf',phone:'+964 750 881 3209',source:'Referral',budget:'$350k+',agent:'Sara',status:'Negotiation',score:96,last:'1 hr ago'},
{id:4,name:'Lana Aziz',phone:'+964 770 993 7280',source:'Instagram',budget:'$140k–$170k',agent:'Ava',status:'Contacted',score:64,last:'3 hrs ago'},
{id:5,name:'Karwan Jalal',phone:'+964 751 222 9910',source:'Walk-in',budget:'$250k–$300k',agent:'Omar',status:'Reserved',score:89,last:'Yesterday'}];
const properties=[
{id:1,title:'Modern Villa in Dream City',location:'Dream City, Erbil',price:'$285,000',beds:4,baths:5,area:'420 m²',status:'Available',img:'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=80'},
{id:2,title:'Skyline Apartment',location:'Empire World, Erbil',price:'$145,000',beds:3,baths:2,area:'185 m²',status:'Reserved',img:'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1000&q=80'},
{id:3,title:'Luxury Family House',location:'English Village, Erbil',price:'$330,000',beds:5,baths:6,area:'510 m²',status:'Sold',img:'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1000&q=80'},
{id:4,title:'City Center Office',location:'Gulan Street, Erbil',price:'$210,000',beds:0,baths:2,area:'230 m²',status:'Available',img:'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1000&q=80'},
{id:5,title:'Garden Residence',location:'Italian Village 1, Erbil',price:'$198,000',beds:4,baths:4,area:'360 m²',status:'Reserved',img:'https://images.unsplash.com/photo-1605146769289-440113cc3d00?auto=format&fit=crop&w=1000&q=80'},
{id:6,title:'Premium Penthouse',location:'Empire Diamond, Erbil',price:'$410,000',beds:4,baths:4,area:'390 m²',status:'Available',img:'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1000&q=80'}];
const contracts=[['CTR-2026-041','Ahmed Kareem','Modern Villa in Dream City','$285,000','Awaiting signature','Jul 15, 2026'],['CTR-2026-040','Karwan Jalal','Garden Residence','$198,000','Signed','Jul 12, 2026'],['CTR-2026-039','Mohammed Rauf','Luxury Family House','$330,000','Draft','Jul 10, 2026']];
function renderNav(){document.getElementById('mainNav').innerHTML=nav.map(g=>`<div class="nav-group">${g[0]}</div>${g[1].map(i=>`<button class="nav-item ${state.page===i[0]?'active':''}" data-page="${i[0]}"><span>${i[1]}</span><span>${i[2]}</span></button>`).join('')}`).join('')}
function header(title,sub,actions=''){return `<div class="page-header"><div><h1>${title}</h1><p>${sub}</p></div><div class="header-actions">${actions}</div></div>`}
function stat(title,value,trend,icon,up=true){return `<div class="stat-card"><div class="stat-top"><span>${title}</span><span class="stat-icon">${icon}</span></div><div class="stat-value">${value}</div><div class="trend ${up?'up':'down'}">${up?'↑':'↓'} ${trend}</div></div>`}
function dashboard(){return `${header('Good morning, Ismail','Here is what is happening across your real estate business today.','<button class="secondary-btn">Export report</button><button class="primary-btn" data-action="new-lead">＋ New lead</button>')}<div class="grid stats-grid">${stat('New leads','24','18% vs last week','◎')}${stat('Active properties','186','7 new this month','⌂')}${stat('Monthly sales','$428k','12.4% vs target','$')}${stat('Pending follow-ups','17','5 overdue','✓',false)}</div><div class="grid dashboard-grid"><div class="panel"><div class="panel-header"><h3>Revenue performance</h3><select class="filter-btn"><option>Last 6 months</option></select></div><div class="chart-bars">${[42,58,49,76,64,92].map((h,i)=>`<div class="bar-wrap"><div class="bar" style="height:${h}%"></div>${['Feb','Mar','Apr','May','Jun','Jul'][i]}</div>`).join('')}</div></div><div class="panel"><div class="panel-header"><h3>Today’s priorities</h3><button class="ghost-btn" data-page="tasks">View all</button></div><div class="list"><div class="list-item"><div class="list-left"><span class="mini-dot" style="background:var(--danger)"></span><div><strong>Call Ahmed Kareem</strong><div class="muted">Follow-up overdue by 2 hours</div></div></div><span class="badge red">Urgent</span></div><div class="list-item"><div class="list-left"><span class="mini-dot" style="background:var(--warning)"></span><div><strong>Contract signing</strong><div class="muted">Karwan Jalal · 2:30 PM</div></div></div><span class="badge yellow">Today</span></div><div class="list-item"><div class="list-left"><span class="mini-dot" style="background:var(--primary)"></span><div><strong>Property viewing</strong><div class="muted">Empire World · 4:00 PM</div></div></div><span class="badge blue">Viewing</span></div></div></div></div><div class="grid dashboard-grid"><div class="panel"><div class="panel-header"><h3>Recent leads</h3><button class="ghost-btn" data-page="leads">Open pipeline →</button></div>${leadTable(leads.slice(0,4),true)}</div><div class="panel"><div class="panel-header"><h3>Property status</h3></div><div class="list"><div class="list-item"><span>Available</span><strong>112</strong></div><div class="list-item"><span>Reserved</span><strong>31</strong></div><div class="list-item"><span>Sold this month</span><strong>18</strong></div><div class="list-item"><span>Off market</span><strong>25</strong></div></div></div></div>`}
function leadTable(data,compact=false){return `<div class="table-wrap" style="box-shadow:none"><table><thead><tr><th>Lead</th><th>Status</th><th>Budget</th><th>Agent</th>${compact?'':'<th>Source</th><th>Score</th><th>Last activity</th>'}</tr></thead><tbody>${data.map(l=>`<tr data-action="lead-detail" data-id="${l.id}"><td><div class="name-cell"><div class="avatar-sm">${l.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div><strong>${l.name}</strong><div class="muted">${l.phone}</div></div></div></td><td><span class="badge ${l.status==='Reserved'?'green':l.status==='Negotiation'?'yellow':'blue'}">${l.status}</span></td><td>${l.budget}</td><td>${l.agent}</td>${compact?'':`<td>${l.source}</td><td><strong>${l.score}</strong></td><td>${l.last}</td>`}</tr>`).join('')}</tbody></table></div>`}
function leadsPage(){return `${header('Leads & Sales Pipeline','Capture, qualify, assign, and convert every opportunity.','<button class="secondary-btn">Import leads</button><button class="primary-btn" data-action="new-lead">＋ New lead</button>')}<div class="toolbar"><div class="search-box">⌕<input id="leadSearch" placeholder="Search leads..."/></div><div class="filters">${['All','New','Contacted','Viewing','Negotiation','Reserved'].map(x=>`<button class="filter-btn ${state.leadFilter===x?'active':''}" data-lead-filter="${x}">${x}</button>`).join('')}</div></div><div class="kanban">${['New','Contacted','Viewing','Negotiation','Reserved'].map(s=>`<div class="kanban-col"><div class="kanban-head"><strong>${s}</strong><span class="badge gray">${leads.filter(l=>l.status===s).length}</span></div>${leads.filter(l=>l.status===s).map(l=>`<div class="deal-card" data-action="lead-detail" data-id="${l.id}"><h4>${l.name}</h4><p>${l.budget}</p><p>${l.source} · ${l.agent}</p><div style="display:flex;justify-content:space-between;margin-top:10px"><span class="badge blue">Score ${l.score}</span><span class="muted">${l.last}</span></div></div>`).join('')||'<div class="empty">No leads</div>'}</div>`).join('')}</div>`}
function clientsPage(){return `${header('Clients','A complete view of buyers, sellers, owners, and investors.','<button class="secondary-btn">Export</button><button class="primary-btn" data-action="new-client">＋ Add client</button>')}<div class="toolbar"><div class="search-box">⌕<input placeholder="Search clients..."/></div><div class="filters"><button class="filter-btn active">All clients</button><button class="filter-btn">Buyers</button><button class="filter-btn">Owners</button><button class="filter-btn">Investors</button></div></div>${leadTable(leads)}`}
function propertiesPage(){let list=state.propertyFilter==='All'?properties:properties.filter(p=>p.status===state.propertyFilter);return `${header('Properties','Manage listings, availability, owners, documents, and sales status.','<button class="secondary-btn">Import properties</button><button class="primary-btn" data-action="new-property">＋ Add property</button>')}<div class="toolbar"><div class="search-box">⌕<input id="propertySearch" placeholder="Search properties..."/></div><div class="filters">${['All','Available','Reserved','Sold'].map(x=>`<button class="filter-btn ${state.propertyFilter===x?'active':''}" data-property-filter="${x}">${x}</button>`).join('')}</div></div><div class="grid property-grid">${list.map(propertyCard).join('')}</div>`}
function propertyCard(p){return `<div class="property-card" data-action="property-detail" data-id="${p.id}"><div class="property-img" style="background-image:url('${p.img}')"><span class="property-price">${p.price}</span><span class="property-status badge ${p.status==='Available'?'green':p.status==='Reserved'?'yellow':'red'}">${p.status}</span></div><div class="property-body"><h3>${p.title}</h3><div class="muted">⌖ ${p.location}</div><div class="property-meta"><span>🛏 ${p.beds||'Office'}</span><span>🛁 ${p.baths}</span><span>▱ ${p.area}</span></div><div class="property-actions"><span class="muted">ID #PR-${1000+p.id}</span><button class="secondary-btn">View details</button></div></div></div>`}
function mapPage(){return `${header('Property Map','Explore inventory geographically and compare nearby listings.','<button class="secondary-btn">Map filters</button><button class="primary-btn" data-action="new-property">＋ Add property</button>')}<div class="panel" style="height:680px;padding:0;overflow:hidden;position:relative;background:linear-gradient(145deg,#dce9d5,#c7d9e8)"><div style="position:absolute;inset:0;background-image:linear-gradient(rgba(255,255,255,.2) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.2) 1px,transparent 1px);background-size:38px 38px"></div><div style="position:absolute;left:5%;top:5%;background:var(--panel);padding:12px;border-radius:12px;box-shadow:var(--shadow);width:280px"><strong>Erbil property map</strong><div class="muted" style="margin-top:4px">186 listings · Live availability</div></div>${properties.map((p,i)=>`<button data-action="property-detail" data-id="${p.id}" style="position:absolute;left:${20+(i*13)%65}%;top:${25+(i*17)%55}%;border:0;background:${p.status==='Available'?'var(--success)':p.status==='Reserved'?'var(--warning)':'var(--danger)'};color:#fff;padding:8px 10px;border-radius:99px;box-shadow:var(--shadow);cursor:pointer">${p.price}</button>`).join('')}<div style="position:absolute;right:18px;bottom:18px;background:var(--panel);border-radius:12px;padding:12px;box-shadow:var(--shadow)"><div><span class="mini-dot" style="display:inline-block;background:var(--success)"></span> Available</div><div style="margin-top:7px"><span class="mini-dot" style="display:inline-block;background:var(--warning)"></span> Reserved</div><div style="margin-top:7px"><span class="mini-dot" style="display:inline-block;background:var(--danger)"></span> Sold</div></div></div>`}
function whatsappPage(){return `${header('WhatsApp Hub','Manage all sales conversations from one unified workspace.','<button class="secondary-btn">Templates</button><button class="primary-btn">＋ New conversation</button>')}<div class="whatsapp-layout"><div class="chat-list"><div class="chat-search"><div class="search-box" style="min-width:0">⌕<input placeholder="Search chats"/></div></div>${leads.map((l,i)=>`<div class="chat-item ${i===0?'active':''}"><div class="name-cell"><div class="avatar-sm">${l.name[0]}</div><div style="flex:1"><div style="display:flex;justify-content:space-between"><strong>${l.name}</strong><span class="muted">${i+9}:2${i}</span></div><div class="muted">${i===0?'Can we schedule a viewing today?':'Thank you, I will review it.'}</div></div></div></div>`).join('')}</div><div class="chat-main"><div class="chat-head"><div class="name-cell"><div class="avatar-sm">AK</div><div><strong>Ahmed Kareem</strong><div class="muted">Online · Assigned to Sara</div></div></div><div><button class="icon-btn">☎</button><button class="icon-btn">⋯</button></div></div><div class="messages"><div class="bubble in">Hello, I saw the villa in Dream City on Facebook. Is it still available?</div><div class="bubble out">Hi Ahmed, yes, it is currently available. It has 4 bedrooms and a 420 m² area.</div><div class="bubble in">Can we schedule a viewing today?</div><div class="bubble out">Certainly. We have availability at 4:00 PM or 6:30 PM. Which works better for you?</div></div><div class="composer"><button class="icon-btn">＋</button><input id="messageInput" placeholder="Type a message..."/><button class="primary-btn" data-action="send-message">Send</button></div></div><div class="contact-side"><div class="name-cell"><div class="avatar">AK</div><div><strong>Ahmed Kareem</strong><div class="muted">Hot lead · Score 92</div></div></div><div class="list" style="margin-top:18px"><div class="list-item"><span>Budget</span><strong>$180k–$220k</strong></div><div class="list-item"><span>Interest</span><strong>Villa</strong></div><div class="list-item"><span>Preferred area</span><strong>Dream City</strong></div><div class="list-item"><span>Agent</span><strong>Sara</strong></div></div><button class="secondary-btn" style="width:100%;margin-top:16px">Open full client profile</button></div></div>`}
function calendarPage(){const days=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];let cells='';for(let i=1;i<=35;i++){let d=i-3;cells+=`<div class="cal-cell"><span class="muted">${d>0&&d<=31?d:''}</span>${d===17?'<div class="event">10:00 Lead follow-up</div><div class="event">16:00 Property viewing</div>':''}${d===19?'<div class="event">14:30 Contract signing</div>':''}${d===23?'<div class="event">11:00 Team meeting</div>':''}</div>`}return `${header('Calendar','Viewings, calls, meetings, payment dates, and contract appointments.','<button class="secondary-btn">Today</button><button class="primary-btn">＋ New event</button>')}<div class="toolbar"><div><button class="icon-btn">←</button><strong style="margin:0 12px">July 2026</strong><button class="icon-btn">→</button></div><div class="filters"><button class="filter-btn active">Month</button><button class="filter-btn">Week</button><button class="filter-btn">Day</button></div></div><div style="overflow:auto"><div class="calendar-grid">${days.map(d=>`<div class="cal-cell cal-head">${d}</div>`).join('')}${cells}</div></div>`}
function tasksPage(){return `${header('Tasks','Keep every follow-up and operational activity on schedule.','<button class="secondary-btn">My tasks</button><button class="primary-btn">＋ New task</button>')}<div class="grid dashboard-grid"><div class="panel"><div class="panel-header"><h3>Task board</h3><span class="badge red">5 overdue</span></div><div class="list">${['Call Ahmed about today’s viewing','Upload ownership document for PR-1002','Prepare contract for Karwan Jalal','Follow up with 6 Facebook leads','Confirm deposit payment'].map((x,i)=>`<div class="list-item"><div class="list-left"><input type="checkbox"><div><strong>${x}</strong><div class="muted">${i<2?'Due today':'Due this week'} · Assigned to ${['Sara','Omar','Legal','Ava','Finance'][i]}</div></div></div><span class="badge ${i<2?'red':'blue'}">${i<2?'High':'Normal'}</span></div>`).join('')}</div></div><div class="panel"><div class="panel-header"><h3>Completion</h3></div><div style="font-size:54px;font-weight:800">76%</div><div class="muted">38 of 50 tasks completed this week</div><div style="height:10px;background:var(--panel-2);border-radius:99px;margin-top:20px"><div style="width:76%;height:100%;background:var(--primary);border-radius:99px"></div></div></div></div>`}
function contractsPage(){return `${header('Contracts','Generate, review, sign, print, and archive property agreements.','<button class="secondary-btn">Templates</button><button class="primary-btn" data-action="new-contract">＋ New contract</button>')}<div class="table-wrap"><table><thead><tr><th>Contract</th><th>Client</th><th>Property</th><th>Value</th><th>Status</th><th>Date</th><th></th></tr></thead><tbody>${contracts.map(c=>`<tr><td><strong>${c[0]}</strong></td><td>${c[1]}</td><td>${c[2]}</td><td>${c[3]}</td><td><span class="badge ${c[4]==='Signed'?'green':c[4]==='Draft'?'gray':'yellow'}">${c[4]}</span></td><td>${c[5]}</td><td><button class="icon-btn">⋯</button></td></tr>`).join('')}</tbody></table></div>`}
function financePage(){return `${header('Finance','Track deposits, installments, commissions, expenses, and outstanding balances.','<button class="secondary-btn">Export statement</button><button class="primary-btn">＋ Record payment</button>')}<div class="grid stats-grid">${stat('Revenue this month','$428,300','12.4% vs June','$')}${stat('Outstanding','$84,500','8 payments pending','⌛',false)}${stat('Commission payable','$31,240','Across 7 agents','♙')}${stat('Operating expenses','$22,810','4.2% below budget','▤')}</div><div class="grid dashboard-grid"><div class="panel"><div class="panel-header"><h3>Recent transactions</h3></div><div class="list">${[['Deposit received','Ahmed Kareem','+$28,500','green'],['Agent commission','Sara Mohammed','-$8,550','red'],['Reservation payment','Karwan Jalal','+$19,800','green'],['Marketing expense','Meta Ads','-$1,200','red']].map(x=>`<div class="list-item"><div><strong>${x[0]}</strong><div class="muted">${x[1]} · Jul ${12+Math.floor(Math.random()*5)}</div></div><strong style="color:var(--${x[3]==='green'?'success':'danger'})">${x[2]}</strong></div>`).join('')}</div></div><div class="panel"><div class="panel-header"><h3>Cash flow</h3></div><div class="chart-bars">${[60,45,78,62,90].map((h,i)=>`<div class="bar-wrap"><div class="bar" style="height:${h}%"></div>W${i+1}</div>`).join('')}</div></div></div>`}
function reportsPage(){return `${header('Reports & Analytics','Understand performance, conversion, inventory, and team productivity.','<button class="secondary-btn">Schedule report</button><button class="primary-btn">Export PDF</button>')}<div class="grid stats-grid">${stat('Lead conversion','18.7%','2.4 points','↗')}${stat('Average deal cycle','26 days','4 days faster','◷')}${stat('Average sale value','$237k','9.1% increase','$')}${stat('Lead response time','8 min','3 min faster','⚡')}</div><div class="grid dashboard-grid"><div class="panel"><div class="panel-header"><h3>Lead sources</h3></div><div class="list">${[['Facebook',38],['WhatsApp',29],['Referrals',18],['Instagram',10],['Walk-in',5]].map(x=>`<div><div style="display:flex;justify-content:space-between;margin-bottom:6px"><span>${x[0]}</span><strong>${x[1]}%</strong></div><div style="height:8px;background:var(--panel-2);border-radius:99px"><div style="width:${x[1]}%;height:100%;background:var(--primary);border-radius:99px"></div></div></div>`).join('')}</div></div><div class="panel"><div class="panel-header"><h3>Top agents</h3></div><div class="list">${[['Sara Mohammed','$186k','12 deals'],['Omar Khalid','$142k','9 deals'],['Ava Rashid','$98k','7 deals']].map((x,i)=>`<div class="list-item"><div class="name-cell"><div class="avatar-sm">${i+1}</div><div><strong>${x[0]}</strong><div class="muted">${x[2]}</div></div></div><strong>${x[1]}</strong></div>`).join('')}</div></div></div>`}
function teamPage(){return `${header('Team & Commissions','Manage agents, roles, targets, access, and commission payouts.','<button class="secondary-btn">Commission rules</button><button class="primary-btn">＋ Invite team member</button>')}<div class="table-wrap"><table><thead><tr><th>Agent</th><th>Role</th><th>Active leads</th><th>Closed deals</th><th>Revenue</th><th>Commission</th><th>Status</th></tr></thead><tbody>${[['Sara Mohammed','Senior Agent',18,12,'$186,000','$8,550'],['Omar Khalid','Sales Agent',21,9,'$142,000','$6,380'],['Ava Rashid','Sales Agent',13,7,'$98,000','$4,410'],['Rebaz Ahmed','Team Lead',8,5,'$85,000','$3,825']].map(x=>`<tr><td><div class="name-cell"><div class="avatar-sm">${x[0].split(' ').map(y=>y[0]).join('')}</div><strong>${x[0]}</strong></div></td><td>${x[1]}</td><td>${x[2]}</td><td>${x[3]}</td><td>${x[4]}</td><td>${x[5]}</td><td><span class="badge green">Active</span></td></tr>`).join('')}</tbody></table></div>`}
function packagesPage(){return `${header('Packages & Modules','Control what each customer receives without maintaining separate versions.','<button class="secondary-btn">Billing settings</button><button class="primary-btn">＋ Create package</button>')}<div class="package-grid"><div class="package"><h3>Starter</h3><div class="muted">For small teams beginning with CRM</div><div class="price">$49<span class="muted" style="font-size:13px">/month</span></div><div class="feature-list"><span>✓ 5 users</span><span>✓ CRM & leads</span><span>✓ Property management</span><span>✓ Tasks & calendar</span><span>— WhatsApp Hub</span><span>— AI features</span></div><button class="secondary-btn" style="width:100%;margin-top:18px">Edit package</button></div><div class="package featured"><span class="badge blue" style="position:absolute;right:14px;top:14px">Most popular</span><h3>Professional</h3><div class="muted">Complete operations for growing agencies</div><div class="price">$149<span class="muted" style="font-size:13px">/month</span></div><div class="feature-list"><span>✓ 20 users</span><span>✓ Everything in Starter</span><span>✓ WhatsApp Hub</span><span>✓ Contracts & finance</span><span>✓ Map & portal</span><span>— AI features</span></div><button class="primary-btn" style="width:100%;margin-top:18px">Current package</button></div><div class="package"><h3>Enterprise</h3><div class="muted">AI, customization, and enterprise controls</div><div class="price">$399<span class="muted" style="font-size:13px">/month</span></div><div class="feature-list"><span>✓ Unlimited users</span><span>✓ Everything in Professional</span><span>✓ AI assistant & OCR</span><span>✓ API & SSO</span><span>✓ White-labeling</span><span>✓ Priority support</span></div><button class="secondary-btn" style="width:100%;margin-top:18px">Edit package</button></div></div><div class="panel" style="margin-top:16px"><div class="panel-header"><h3>Professional plan module controls</h3><span class="badge green">Active</span></div>${['CRM & Leads','Property Management','WhatsApp Hub','Contracts','Finance','Customer Portal','AI Assistant','Marketing Automation','Advanced Analytics'].map((x,i)=>`<div class="toggle-row"><div><strong>${x}</strong><div class="muted">${i<6?'Included in current package':'Available as paid add-on'}</div></div><div class="switch ${i<6?'on':''}" data-action="toggle-module"></div></div>`).join('')}</div>`}
function settingsPage(){return `${header('Settings','Configure company information, branding, roles, security, and integrations.','<button class="primary-btn">Save changes</button>')}<div class="split"><div class="panel"><div class="panel-header"><h3>Company profile</h3></div><div class="form-grid"><div class="field"><label>Company name</label><input value="Noor Properties"/></div><div class="field"><label>Business email</label><input value="info@noorproperties.com"/></div><div class="field"><label>Phone</label><input value="+964 750 000 0000"/></div><div class="field"><label>Currency</label><select><option>USD</option><option>IQD</option></select></div><div class="field full"><label>Office address</label><input value="Gulan Street, Erbil, Iraq"/></div></div></div><div class="panel"><div class="panel-header"><h3>Security</h3></div><div class="toggle-row"><span>Multi-factor authentication</span><div class="switch on"></div></div><div class="toggle-row"><span>Session timeout</span><strong>30 min</strong></div><div class="toggle-row"><span>Audit logging</span><div class="switch on"></div></div><button class="secondary-btn" style="width:100%;margin-top:14px">View audit log</button></div></div><div class="panel" style="margin-top:16px"><div class="panel-header"><h3>Integrations</h3></div><div class="grid stats-grid">${['WhatsApp Business','Google Calendar','Microsoft 365','OpenAI'].map((x,i)=>`<div class="stat-card" style="box-shadow:none"><div class="stat-top"><strong>${x}</strong><span class="badge ${i<2?'green':'gray'}">${i<2?'Connected':'Not connected'}</span></div><button class="secondary-btn" style="margin-top:18px;width:100%">${i<2?'Manage':'Connect'}</button></div>`).join('')}</div></div>`}
function render(){renderNav();const views={dashboard,leads:leadsPage,clients:clientsPage,properties:propertiesPage,map:mapPage,whatsapp:whatsappPage,calendar:calendarPage,tasks:tasksPage,contracts:contractsPage,finance:financePage,reports:reportsPage,team:teamPage,packages:packagesPage,settings:settingsPage};document.getElementById('pageContent').innerHTML=(views[state.page]||dashboard)();bindDynamic()}
function modal(title,body,footer='<button class="secondary-btn" data-action="close-modal">Cancel</button><button class="primary-btn" data-action="save-modal">Save</button>'){document.getElementById('modal').innerHTML=`<div class="modal-header"><h3 style="margin:0">${title}</h3><button class="icon-btn" data-action="close-modal">✕</button></div><div class="modal-body">${body}</div><div class="modal-footer">${footer}</div>`;document.getElementById('modalBackdrop').classList.remove('hidden');bindDynamic()}
function closeModal(){document.getElementById('modalBackdrop').classList.add('hidden')}
function formBody(type){return `<div class="form-grid"><div class="field"><label>Name / title</label><input placeholder="Enter ${type.toLowerCase()} name"/></div><div class="field"><label>Status</label><select><option>New</option><option>Active</option><option>Pending</option></select></div><div class="field"><label>Phone / reference</label><input placeholder="Enter value"/></div><div class="field"><label>Assigned agent</label><select><option>Sara</option><option>Omar</option><option>Ava</option></select></div><div class="field full"><label>Notes</label><textarea rows="4" placeholder="Add details..."></textarea></div></div>`}
function toast(msg){const el=document.createElement('div');el.className='toast';el.innerHTML=`<strong>${msg}</strong><div class="muted">Demo action completed successfully.</div>`;document.getElementById('toastArea').appendChild(el);setTimeout(()=>el.remove(),2600)}
function bindDynamic(){
  document.querySelectorAll('[data-page]').forEach(el=>{
    el.onclick=()=>{state.page=el.dataset.page;document.getElementById('sidebar').classList.remove('open');render();};
  });
  document.querySelectorAll('[data-property-filter]').forEach(el=>{
    el.onclick=()=>{state.propertyFilter=el.dataset.propertyFilter;render();};
  });
  document.querySelectorAll('[data-lead-filter]').forEach(el=>{
    el.onclick=()=>{state.leadFilter=el.dataset.leadFilter;render();};
  });
  document.querySelectorAll('[data-action]').forEach(el=>{
    el.onclick=()=>{
      const a=el.dataset.action;
      if(a==='new-lead') modal('Create new lead',formBody('Lead'));
      if(a==='new-client') modal('Add client',formBody('Client'));
      if(a==='new-property') modal('Add property',formBody('Property'));
      if(a==='new-contract') modal('Generate contract',formBody('Contract'));
      if(a==='quick-create') modal('Quick create',`<div class="grid stats-grid">${['Lead','Property','Client','Contract'].map(x=>`<button class="stat-card" style="cursor:pointer;text-align:left" data-action="new-${x.toLowerCase()}"><span class="stat-icon">＋</span><div style="margin-top:12px"><strong>${x}</strong></div></button>`).join('')}</div>`,'<button class="secondary-btn" data-action="close-modal">Close</button>');
      if(a==='close-modal') closeModal();
      if(a==='save-modal'){closeModal();toast('Saved successfully');}
      if(a==='property-detail'){
        const p=properties.find(x=>x.id==el.dataset.id);
        modal(p.title,`<img src="${p.img}" style="width:100%;height:260px;object-fit:cover;border-radius:14px"><div class="grid stats-grid" style="margin-top:14px">${stat('Price',p.price,'Asking price','$')}${stat('Area',p.area,'Total area','▱')}${stat('Bedrooms',p.beds||'Office','Property type','🛏')}${stat('Status',p.status,'Current availability','●')}</div><div class="panel" style="margin-top:14px;box-shadow:none"><strong>${p.location}</strong><p class="muted">Property details, owner records, documents, activity timeline, reservation history, and agent notes appear here.</p></div>`,'<button class="secondary-btn" data-action="close-modal">Close</button><button class="primary-btn" data-action="save-modal">Reserve property</button>');
      }
      if(a==='lead-detail'){
        const l=leads.find(x=>x.id==el.dataset.id);
        modal(l.name,`<div class="split"><div><div class="panel" style="box-shadow:none"><div class="name-cell"><div class="avatar">${l.name[0]}</div><div><strong>${l.name}</strong><div class="muted">${l.phone}</div></div></div><div class="list" style="margin-top:16px"><div class="list-item"><span>Status</span><span class="badge blue">${l.status}</span></div><div class="list-item"><span>Budget</span><strong>${l.budget}</strong></div><div class="list-item"><span>Source</span><strong>${l.source}</strong></div><div class="list-item"><span>Agent</span><strong>${l.agent}</strong></div></div></div></div><div class="panel" style="box-shadow:none"><strong>Activity timeline</strong><div class="list" style="margin-top:14px"><div class="list-item">Lead created</div><div class="list-item">WhatsApp message received</div><div class="list-item">Viewing scheduled</div></div></div></div>`,'<button class="secondary-btn" data-action="close-modal">Close</button><button class="primary-btn" data-action="save-modal">Add activity</button>');
      }
      if(a==='send-message'){
        const input=document.getElementById('messageInput');
        if(input&&input.value.trim()){
          const box=document.querySelector('.messages');
          box.insertAdjacentHTML('beforeend',`<div class="bubble out">${input.value}</div>`);
          input.value='';box.scrollTop=box.scrollHeight;
        }
      }
      if(a==='toggle-module'){el.classList.toggle('on');toast(el.classList.contains('on')?'Module enabled':'Module disabled');}
      if(a==='open-packages'){state.page='packages';render();}
      if(a==='notifications') modal('Notifications','<div class="list"><div class="list-item">New lead assigned to Sara</div><div class="list-item">Reservation expires tomorrow</div><div class="list-item">Deposit payment received</div><div class="list-item">Contract awaiting signature</div></div>','<button class="secondary-btn" data-action="close-modal">Close</button>');
    };
  });
}
document.getElementById('mobileMenu').onclick=()=>document.getElementById('sidebar').classList.toggle('open');document.getElementById('themeToggle').onclick=()=>{document.body.classList.toggle('dark');state.theme=document.body.classList.contains('dark')?'dark':'light'};document.getElementById('modalBackdrop').onclick=e=>{if(e.target.id==='modalBackdrop')closeModal()};document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();document.getElementById('searchInput').focus()}if(e.key==='Escape')closeModal()});render();
