'use client';
import {useState} from 'react';
import AppShell from '@/components/AppShell';
import {Modal,PageHeader,Status} from '@/components/UI';
import {ChevronLeft,ChevronRight} from 'lucide-react';

const stages=['New lead','Contacted','Qualified','Viewing scheduled','Viewing completed','Negotiation','Offer submitted','Contract preparation','Closed won','Closed lost'];
type Deal={id:number;contact:string;property:string;type:string;agent:string;stage:string;from:number;to:number;date:string};
const seed:Deal[]=[
{id:1,contact:'Ari Hassan',property:'Empire Pearl 2BR Apartment',type:'Purchase',agent:'Self',stage:'New lead',from:78000,to:90000,date:'2026-08-12'},
{id:2,contact:'Lana Kareem',property:'Commercial Shop on 100m Road',type:'Property listing',agent:'Roj Ahmed',stage:'Contacted',from:1800,to:2200,date:'2026-08-05'},
{id:3,contact:'Omar Salih',property:'Dream City Villa 14',type:'Purchase',agent:'Sara Karim',stage:'Qualified',from:310000,to:350000,date:'2026-09-01'},
{id:4,contact:'Dilan Ahmed',property:'Italian Village Apartment',type:'Rental',agent:'Self',stage:'Viewing scheduled',from:900,to:1100,date:'2026-08-02'},
{id:5,contact:'Karwan Aziz',property:'Gulan Office 402',type:'Rental',agent:'Roj Ahmed',stage:'Viewing completed',from:1500,to:1700,date:'2026-08-07'},
{id:6,contact:'Shilan Mahmood',property:'English Village House',type:'Purchase',agent:'Sara Karim',stage:'Negotiation',from:210000,to:230000,date:'2026-08-21'},
{id:7,contact:'Rebin Omer',property:'Ankawa Family Apartment',type:'Purchase',agent:'Self',stage:'Offer submitted',from:125000,to:132000,date:'2026-08-10'},
{id:8,contact:'Narin Ali',property:'Mass City Studio',type:'Purchase',agent:'Roj Ahmed',stage:'Contract preparation',from:68000,to:70000,date:'2026-08-04'}];

export default function DealsModule(){
 const [rows,setRows]=useState(seed),[show,setShow]=useState(false),[error,setError]=useState('');
 const move=(id:number,delta:number)=>setRows(rows.map(r=>r.id===id?{...r,stage:stages[Math.max(0,Math.min(stages.length-1,stages.indexOf(r.stage)+delta))]}:r));
 const drop=(id:number,stage:string)=>setRows(rows.map(r=>r.id===id?{...r,stage}:r));
 function add(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError('');const f=new FormData(e.currentTarget);const from=Number(f.get('from')),to=Number(f.get('to'));const date=String(f.get('date'));const today=new Date().toISOString().slice(0,10);if(to<from){setError('Estimated value to must be equal to or greater than estimated value from.');return}if(date<today){setError('Expected closing date must be today or a future date.');return}setRows([{id:Date.now(),contact:String(f.get('contact')),property:String(f.get('property')),type:String(f.get('type')),agent:String(f.get('agent')),stage:String(f.get('stage')),from,to,date},...rows]);setShow(false)}
 return <AppShell><PageHeader title="Deals" subtitle="Sales opportunities and pipeline" action="Add Deal" onAction={()=>setShow(true)}/><div className="kanban compact-kanban">{stages.map(stage=><section className="kanban-col" key={stage} onDragOver={e=>e.preventDefault()} onDrop={e=>drop(Number(e.dataTransfer.getData('dealId')),stage)}><header><strong>{stage}</strong><span>{rows.filter(r=>r.stage===stage).length}</span></header>{rows.filter(r=>r.stage===stage).map(r=>{const i=stages.indexOf(r.stage);return <article className="deal-card" draggable onDragStart={e=>e.dataTransfer.setData('dealId',String(r.id))} key={r.id}><small>{r.type}</small><h3>{r.contact} — {r.property}</h3><p>${r.from.toLocaleString()} – ${r.to.toLocaleString()}</p><p>Expected: {r.date}</p><div className="deal-footer"><Status tone="neutral">{r.agent}</Status><div className="stage-arrows">{i>0&&<button onClick={()=>move(r.id,-1)} aria-label="Move back"><ChevronLeft size={16}/></button>}{i<stages.length-1&&<button onClick={()=>move(r.id,1)} aria-label="Move forward"><ChevronRight size={16}/></button>}</div></div></article>})}</section>)}</div>{show&&<Modal title="Add Deal" onClose={()=>setShow(false)} wide><form onSubmit={add}><p className="form-note">The title is generated automatically from the selected contact and property.</p>{error&&<p className="error-box">{error}</p>}<div className="form-grid"><label>Contact *<select name="contact"><option>Ari Hassan</option><option>Lana Kareem</option><option>Omar Salih</option></select></label><label>Property *<select name="property"><option>Empire Pearl 2BR Apartment</option><option>Commercial Shop on 100m Road</option><option>Dream City Villa 14</option></select></label><label>Deal type<select name="type"><option>Purchase</option><option>Sale</option><option>Rental</option><option>Property listing</option><option>Investment</option><option>Other</option></select></label><label>Assign to<select name="agent"><option>Self</option><option>Roj Ahmed</option><option>Sara Karim</option></select></label><label>Stage<select name="stage">{stages.map(x=><option key={x}>{x}</option>)}</select></label><label>Currency<select><option>USD</option><option>IQD</option></select></label><label>Estimated value from<input name="from" type="number" min="0" required/></label><label>Estimated value to<input name="to" type="number" min="0" required/></label><label className="span-2">Expected closing date<input name="date" type="date" min={new Date().toISOString().slice(0,10)} required/></label><label className="span-2">Next action<textarea rows={2}/></label></div><div className="modal-actions"><button type="button" className="btn ghost" onClick={()=>setShow(false)}>Cancel</button><button className="btn">Add Deal</button></div></form></Modal>}</AppShell>}
