'use client';
import {useEffect,useState} from 'react';import {createClient} from '@/lib/supabase/client';

type Kind='branches'|'teams'|'employees';
export default function SimpleCrud({kind,branchId}:{kind:Kind;branchId:string}){const supabase=createClient();const [rows,setRows]=useState<any[]>([]);const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const [form,setForm]=useState<any>({});const title=kind==='branches'?'Branch':kind==='teams'?'Team':'Employee';
async function load(){let q=supabase.from(kind).select('*').order('created_at',{ascending:false});if(kind!=='branches')q=q.eq('branch_id',branchId);const {data}=await q;setRows(data||[])}useEffect(()=>{load()},[]);
async function save(e:React.FormEvent){e.preventDefault();setBusy(true);const payload=kind==='branches'?form:{...form,branch_id:branchId};if(kind==='employees')payload.status='active';await supabase.from(kind).insert(payload);setOpen(false);setForm({});await load();setBusy(false)}
async function archive(id:string){if(!confirm(`Archive this ${title.toLowerCase()}?`))return;if(kind==='employees')await supabase.from(kind).update({status:'archived'}).eq('id',id);else await supabase.from(kind).delete().eq('id',id);await load()}
return <><button className="btn btn-primary" onClick={()=>setOpen(true)}>+ New {title}</button><div style={{height:16}}/><div className="table-wrap"><table><thead><tr><th>Name</th><th>Details</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.name||`${r.first_name||''} ${r.last_name||''}`}</strong></td><td>{r.city||r.description||r.job_title||'—'}</td><td><span className="badge badge-success">{r.status||'active'}</span></td><td><button className="icon-btn" onClick={()=>archive(r.id)}>Archive</button></td></tr>)}{!rows.length&&<tr><td colSpan={4} className="empty">No records yet.</td></tr>}</tbody></table></div>{open&&<div className="modal-backdrop"><div className="modal"><div className="modal-head"><h2>Create {title}</h2><button className="icon-btn" onClick={()=>setOpen(false)}>✕</button></div><form onSubmit={save} className="form-grid">{kind==='branches'?<><Field label="Name" name="name" set={setForm}/><Field label="City" name="city" value="Erbil" set={setForm}/><Field label="Region" name="region" value="Kurdistan Region" set={setForm}/><Field label="Country" name="country" value="Iraq" set={setForm}/></>:kind==='teams'?<><Field label="Team name" name="name" set={setForm}/><Field label="Description" name="description" set={setForm}/></>:<><Field label="First name" name="first_name" set={setForm}/><Field label="Last name" name="last_name" set={setForm}/><Field label="Work email" name="work_email" type="email" set={setForm}/><Field label="Phone" name="phone" set={setForm}/><Field label="Job title" name="job_title" set={setForm}/><Field label="Start date" name="start_date" type="date" set={setForm}/></>}<div className="form-actions span-2"><button type="button" className="btn btn-secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn btn-primary" disabled={busy}>Create</button></div></form></div></div>}</>}
function Field({label,name,set,value='',type='text'}:{label:string;name:string;set:any;value?:string;type?:string}){return <div className="field"><label>{label}</label><input className="input" type={type} required={['name','first_name','last_name'].includes(name)} defaultValue={value} onChange={e=>set((f:any)=>({...f,[name]:e.target.value}))}/></div>}
