create extension if not exists pgcrypto;
create type public.app_role as enum ('super_admin','branch_admin','branch_manager','sales_manager','agent','hr_manager','finance_manager','viewer');
create type public.member_status as enum ('invited','active','suspended');
create type public.employee_status as enum ('active','on_hold','on_leave','terminated','archived');
create type public.leave_status as enum ('pending','approved','rejected','cancelled');

create table public.organizations(id uuid primary key default gen_random_uuid(),name text not null,created_by uuid not null references auth.users(id),created_at timestamptz not null default now());
create table public.branches(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,name text not null,city text not null,region text,country text not null,status text not null default 'active',created_at timestamptz not null default now());
create table public.branch_memberships(id uuid primary key default gen_random_uuid(),branch_id uuid not null references public.branches(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,role public.app_role not null,status public.member_status not null default 'active',created_at timestamptz not null default now(),unique(branch_id,user_id));
create table public.teams(id uuid primary key default gen_random_uuid(),branch_id uuid not null references public.branches(id) on delete cascade,name text not null,description text,status text not null default 'active',created_at timestamptz not null default now());
create table public.employees(id uuid primary key default gen_random_uuid(),branch_id uuid not null references public.branches(id) on delete cascade,user_id uuid references auth.users(id) on delete set null,team_id uuid references public.teams(id) on delete set null,line_manager_id uuid references public.employees(id) on delete set null,first_name text not null,last_name text not null,work_email text,phone text,job_title text,start_date date,employment_type text,status public.employee_status not null default 'active',created_at timestamptz not null default now(),constraint not_self_manager check (line_manager_id is null or line_manager_id <> id));
create table public.leave_balances(id uuid primary key default gen_random_uuid(),branch_id uuid not null references public.branches(id) on delete cascade,employee_id uuid not null references public.employees(id) on delete cascade,leave_category text not null,entitled numeric(8,2) not null default 0,used numeric(8,2) not null default 0,year int not null default extract(year from current_date),updated_at timestamptz not null default now(),unique(employee_id,leave_category,year));
create table public.leave_requests(id uuid primary key default gen_random_uuid(),branch_id uuid not null references public.branches(id) on delete cascade,employee_id uuid not null references public.employees(id) on delete cascade,leave_category text not null,duration_unit text not null check(duration_unit in ('hourly','half_day','full_day')),start_date date not null,end_date date not null,start_time time,end_time time,reason text,status public.leave_status not null default 'pending',decided_by uuid references auth.users(id),decided_at timestamptz,created_at timestamptz not null default now(),check(end_date>=start_date));
create table public.employee_documents(id uuid primary key default gen_random_uuid(),branch_id uuid not null references public.branches(id) on delete cascade,employee_id uuid not null references public.employees(id) on delete cascade,title text not null,document_type text not null,storage_path text not null,issue_date date,expiry_date date,notes text,created_by uuid not null references auth.users(id),created_at timestamptz not null default now());
create table public.audit_logs(id bigint generated always as identity primary key,branch_id uuid references public.branches(id),actor_id uuid references auth.users(id),action text not null,entity_type text not null,entity_id uuid,old_data jsonb,new_data jsonb,created_at timestamptz not null default now());

create or replace function public.is_branch_member(p_branch uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from branch_memberships where branch_id=p_branch and user_id=auth.uid() and status='active')$$;
create or replace function public.has_branch_role(p_branch uuid,p_roles public.app_role[]) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from branch_memberships where branch_id=p_branch and user_id=auth.uid() and status='active' and role=any(p_roles))$$;
create or replace function public.create_first_branch(p_name text,p_city text,p_region text,p_country text) returns uuid language plpgsql security definer set search_path=public as $$declare org uuid; br uuid;begin if auth.uid() is null then raise exception 'Authentication required'; end if;if exists(select 1 from branch_memberships where user_id=auth.uid()) then raise exception 'Workspace already exists';end if;insert into organizations(name,created_by) values(p_name,auth.uid()) returning id into org;insert into branches(organization_id,name,city,region,country) values(org,p_name,p_city,p_region,p_country) returning id into br;insert into branch_memberships(branch_id,user_id,role,status) values(br,auth.uid(),'super_admin','active');return br;end$$;
grant execute on function public.create_first_branch(text,text,text,text) to authenticated;

alter table organizations enable row level security;alter table branches enable row level security;alter table branch_memberships enable row level security;alter table teams enable row level security;alter table employees enable row level security;alter table leave_balances enable row level security;alter table leave_requests enable row level security;alter table employee_documents enable row level security;alter table audit_logs enable row level security;
create policy org_read on organizations for select using(exists(select 1 from branches b join branch_memberships m on m.branch_id=b.id where b.organization_id=organizations.id and m.user_id=auth.uid() and m.status='active'));
create policy branch_read on branches for select using(is_branch_member(id));
create policy branch_manage on branches for all using(has_branch_role(id,array['super_admin','branch_admin']::app_role[])) with check(has_branch_role(id,array['super_admin','branch_admin']::app_role[]));
create policy membership_read on branch_memberships for select using(is_branch_member(branch_id));
create policy membership_manage on branch_memberships for all using(has_branch_role(branch_id,array['super_admin','branch_admin']::app_role[])) with check(has_branch_role(branch_id,array['super_admin','branch_admin']::app_role[]));
create policy teams_access on teams for all using(is_branch_member(branch_id)) with check(has_branch_role(branch_id,array['super_admin','branch_admin','branch_manager','hr_manager']::app_role[]));
create policy employee_read on employees for select using(is_branch_member(branch_id));
create policy employee_write on employees for all using(has_branch_role(branch_id,array['super_admin','branch_admin','branch_manager','hr_manager']::app_role[])) with check(has_branch_role(branch_id,array['super_admin','branch_admin','branch_manager','hr_manager']::app_role[]));
create policy balance_read on leave_balances for select using(is_branch_member(branch_id));
create policy balance_write on leave_balances for all using(has_branch_role(branch_id,array['super_admin','hr_manager']::app_role[])) with check(has_branch_role(branch_id,array['super_admin','hr_manager']::app_role[]));
create policy request_read on leave_requests for select using(is_branch_member(branch_id));
create policy request_insert on leave_requests for insert with check(is_branch_member(branch_id));
create policy request_update on leave_requests for update using(has_branch_role(branch_id,array['super_admin','hr_manager','branch_manager']::app_role[]));
create policy docs_read on employee_documents for select using(has_branch_role(branch_id,array['super_admin','hr_manager','branch_manager']::app_role[]));
create policy docs_write on employee_documents for all using(has_branch_role(branch_id,array['super_admin','hr_manager']::app_role[])) with check(has_branch_role(branch_id,array['super_admin','hr_manager']::app_role[]));
create policy audit_read on audit_logs for select using(has_branch_role(branch_id,array['super_admin','branch_admin']::app_role[]));

create index idx_memberships_user on branch_memberships(user_id,status);create index idx_employees_branch on employees(branch_id,status);create index idx_leave_requests_branch on leave_requests(branch_id,status);create index idx_docs_employee on employee_documents(employee_id);
