'use client';
import { useMemo,useState } from 'react';
import AppShell from '@/components/AppShell';
import { Empty,FilterButton,Modal,PageHeader,SearchBar,Status } from '@/components/UI';

type Contact={id:number;name:string;types:string[];phone1:string;phone2?:string;email?:string;city:string;budgetFrom:number;budgetTo:number;source:string;status:'Active'|'Do not contact'|'Archived';notes?:string;reason?:string};
const seed:Contact[]=[
{id:1,name:'Ari Hassan',types:['Buyer','Investor'],phone1:'+964 750 123 4567',city:'Erbil',budgetFrom:120000,budgetTo:220000,source:'Friend referral',status:'Active'},
{id:2,name:'Lana Kareem',types:['Landlord'],phone1:'+964 751 222 9911',phone2:'+964 770 441 8822',email:'lana@example.com',city:'Erbil',budgetFrom:0,budgetTo:0,source:'Instagram',status:'Active'},
{id:3,name:'Omar Salih',types:['Seller'],phone1:'+964 750 555 1212',city:'Duhok',budgetFrom:0,budgetTo:0,source:'Networking event',status:'Do not contact',reason:'Asked not to receive any future calls.'}
];
const sources=['Networking event','TikTok','Instagram','Facebook','Friend referral','Website','Walk-in','Property portal','Existing client','Other'];
const types=['Buyer','Seller','Tenant','Landlord','Investor','Developer','Property owner','Broker or partner','Other'];
export default function ContactsModule(){
 const [rows,setRows]=useState(seed),[show,setShow]=useState(false),[filters,setFilters]=useState(false),[q,setQ]=useState('');
 const [type,setType]=useState(''),[city,setCity]=useState(''),[source,setSource]=useState(''),[status,setStatus]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState('');
 const list=useMemo(()=>rows.filter(r=>{const s=q.toLowerCase(); const match=!s||r.name.toLowerCase().includes(s)||r.phone1.includes(q)||(r.phone2||'').includes(q); const overlap=(!from||r.budgetTo>=+from)&&(!to||r.budgetFrom<=+to); return match&&(!type||r.types.includes(type))&&(!city||r.city===city)&&(!source||r.source===source)&&(!status||r.status===status)&&overlap}),[rows,q,type,city,source,status,from,to]);
 function add(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const selected=f.getAll('types') as string[];setRows([{id:Date.now(),name:String(f.get('name')),types:selected,phone1:String(f.get('phone1')),phone2:String(f.get('phone2')||''),email:String(f.get('email')||''),city:String(f.get('city')),budgetFrom:Number(f.get('budgetFrom')||0),budgetTo:Number(f.get('budgetTo')||0),source:String(f.get('source')),status:'Active',notes:String(f.get('notes')||'')},...rows]);setShow(false)}
 function doNotContact(id:number){const reason=window.prompt('Reason for Do Not Contact status:');if(reason?.trim())setRows(rows.map(r=>r.id===id?{...r,status:'Do not contact',reason}:r))}
 return <AppShell><PageHeader title="Contacts" subtitle={`${rows.length} total records`} action="Add Contact" onAction={()=>setShow(true)}/>
 <div className="toolbar"><SearchBar value={q} onChange={setQ} placeholder="Search by name or phone number"/><FilterButton open={filters} onClick={()=>setFilters(!filters)}/></div>
 {filters&&<div className="filters"><select value={type} onChange={e=>setType(e.target.value)}><option value="">All types</option>{types.map(x=><option key={x}>{x}</option>)}</select><select value={city} onChange={e=>setCity(e.target.value)}><option value="">All cities</option><option>Erbil</option><option>Duhok</option><option>Sulaymaniyah</option></select><select value={source} onChange={e=>setSource(e.target.value)}><option value="">All sources</option>{sources.map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option>Active</option><option>Do not contact</option><option>Archived</option></select><input type="number" placeholder="Budget from" value={from} onChange={e=>setFrom(e.target.value)}/><input type="number" placeholder="Budget to" value={to} onChange={e=>setTo(e.target.value)}/><button className="btn ghost" onClick={()=>{setType('');setCity('');setSource('');setStatus('');setFrom('');setTo('')}}>Clear</button></div>}
 <div className="table-wrap">{list.length?<table><thead><tr><th>Contact</th><th>Type</th><th>Phone</th><th>City</th><th>Budget</th><th>Source</th><th>Status</th><th></th></tr></thead><tbody>{list.map(r=><tr key={r.id}><td><strong>{r.name}</strong>{r.email&&<small>{r.email}</small>}</td><td>{r.types.join(', ')}</td><td>{r.phone1}{r.phone2&&<small>{r.phone2}</small>}</td><td>{r.city}</td><td>{r.budgetTo?`$${r.budgetFrom.toLocaleString()} – $${r.budgetTo.toLocaleString()}`:'—'}</td><td>{r.source}</td><td><Status tone={r.status==='Active'?'good':r.status==='Do not contact'?'bad':'neutral'}>{r.status}</Status>{r.reason&&<small>{r.reason}</small>}</td><td>{r.status==='Active'&&<button className="text-danger" onClick={()=>doNotContact(r.id)}>Do not contact</button>}</td></tr>)}</tbody></table>:<Empty title="No contacts found" body="Change your search or filters."/>}</div>
 {show&&<Modal title="Add Contact" onClose={()=>setShow(false)} wide><form onSubmit={add}><div className="form-grid"><label className="span-2">Full name *<input name="name" required placeholder="John Smith"/></label><fieldset className="span-2"><legend>Contact type *</legend><div className="check-grid">{types.map(x=><label className="check" key={x}><input type="checkbox" name="types" value={x}/>{x}</label>)}</div></fieldset><label>Phone number 1 *<input name="phone1" required placeholder="+964 750 000 0000"/></label><label>Phone number 2<input name="phone2" placeholder="Optional"/></label><label>Email<input name="email" type="email" placeholder="Optional"/></label><label>City *<select name="city" required defaultValue="Erbil"><option>Erbil</option><option>Duhok</option><option>Sulaymaniyah</option><option>Other</option></select></label><label>Budget from<input name="budgetFrom" type="number" min="0"/></label><label>Budget to<input name="budgetTo" type="number" min="0"/></label><label className="span-2">Source *<select name="source" required defaultValue=""><option value="" disabled>Select source</option>{sources.map(x=><option key={x}>{x}</option>)}</select></label><label className="span-2">Notes<textarea name="notes" rows={3}/></label></div><div className="modal-actions"><button type="button" className="btn ghost" onClick={()=>setShow(false)}>Cancel</button><button className="btn">Add Contact</button></div></form></Modal>}
 </AppShell>}
